repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest release or specify the version you prefer
    hooks:
      - id: black
        language_version: python3  # Make sure this matches your Python version (e.g., python3 or python3.x)
